name=sqlserver-source-connector
connector.class=io.debezium.connector.sqlserver.SqlServerConnector
tasks.max=1
database.hostname=sqlserver
database.port=1433
database.user=sa
database.password=YourStrong@Passw0rd
database.names=TestDB
database.encrypt=false
database.trustServerCertificate=true
topic.prefix=sqlserver
table.include.list=dbo.users
snapshot.mode=initial
snapshot.locking.mode=none
include.schema.changes=false
schema.history.internal.kafka.bootstrap.servers=kafka:9092
schema.history.internal.kafka.topic=schema-changes.sqlserver
