name=sqlserver-source-connector
connector.class=io.debezium.connector.sqlserver.SqlServerConnector
tasks.max=1
database.hostname=host.docker.internal
database.port=14330
database.user=sa
database.password=YourStrong@Passw0rd
database.names=CDC_Demo
database.encrypt=false
database.trustServerCertificate=true
topic.prefix=local-sqlserver
table.include.list=dbo.Users
snapshot.mode=initial
snapshot.locking.mode=none
include.schema.changes=false
schema.history.internal.kafka.bootstrap.servers=kafka:9092
schema.history.internal.kafka.topic=schema-changes.local-sqlserver
